version: 0.2

phases:
  install:
    commands:
      - echo "Build is Triggered"
  build:
    commands:
      - python -m pytest --junitxml=pytest_reports/pytest_report.xml

reports:
  pytest_reports:
    files:
      - pytest_report.xml
    base-directory: pytest_reports/
    file-format: JUNITXML
